# Generated by Django 3.0.8 on 2020-09-03 19:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20200728_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShippingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=100)),
                ('first_address_line', models.CharField(max_length=75)),
                ('second_address_line', models.CharField(blank=True, max_length=75, null=True)),
                ('town_or_city', models.CharField(max_length=50)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('postcode', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_ordered', models.DateField(blank=True, default=datetime.date.today)),
                ('total', models.IntegerField()),
                ('order_shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.OrderShippingDetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
            ],
        ),
    ]
