# Generated by Django 3.0.8 on 2020-09-03 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200819_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershippingdetails',
            name='order_number',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
