# Generated by Django 3.0.8 on 2020-09-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderlinedetail_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlinedetail',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
