# Generated by Django 3.0.8 on 2020-09-10 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200910_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlinedetail',
            name='size',
            field=models.CharField(max_length=3),
            preserve_default=False,
        ),
    ]
