# Generated by Django 3.0.8 on 2020-07-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('display_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('place', models.CharField(max_length=254)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.ProductGroup')),
            ],
        ),
    ]
