# Generated by Django 3.0.8 on 2020-07-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PrintPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PrintSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_size', models.CharField(max_length=120)),
                ('print_prices', models.ManyToManyField(through='products.PricingSizes', to='products.PrintPrice')),
            ],
        ),
        migrations.AddField(
            model_name='printprice',
            name='print_sizes',
            field=models.ManyToManyField(through='products.PricingSizes', to='products.PrintSize'),
        ),
        migrations.AddField(
            model_name='pricingsizes',
            name='print_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.PrintPrice'),
        ),
        migrations.AddField(
            model_name='pricingsizes',
            name='print_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.PrintSize'),
        ),
    ]
